#!/usr/bin/env python3
"""
run_dynamic_pacing_batch.py - High-Tempo Sentence-Level Batch Production & Deep QA Runner

Orchestrates 4 specialized sub-agents across:
- Episode 1: The Archimedes Claw at Syracuse (archimedes-claw)
- Episode 2: The Fire Ships of Red Cliffs (red-cliffs-fire-ships)
- Episode 3: The Roman Scutum & Testudo Formation at Carrhae (battle-of-carrhae-camel-train)

Generates 14 micro-scenes per video (2.0-3.5s per cut), parallel keyframe synthesis,
rapid Ken Burns camera dynamics, burned kinetic captions, and 5-vector Deep QA.
Archives releases to out/releases_v2/{episode_id}/ and logs to out/DYNAMIC_PACING_REPORT.md.
"""

import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

QUEUE = [
    {
        "id": "archimedes-claw",
        "title": "The Archimedes Claw at Syracuse"
    },
    {
        "id": "red-cliffs-fire-ships",
        "title": "The Fire Ships of Red Cliffs"
    },
    {
        "id": "battle-of-carrhae-camel-train",
        "title": "The Roman Scutum & Testudo Formation at Carrhae"
    }
]

MAX_RETRIES = 4


def log(msg: str):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {msg}", flush=True)


def run_step(cmd: list, desc: str) -> bool:
    log(f"Running: {desc}...")
    res = subprocess.run(cmd)
    if res.returncode != 0:
        log(f"[ERROR] Step '{desc}' failed with exit code {res.returncode}")
        return False
    log(f"[SUCCESS] Completed: {desc}")
    return True


def archive_release_v2(episode_id: str, qa_report: dict):
    release_dir = Path(f"out/releases_v2/{episode_id}")
    release_dir.mkdir(parents=True, exist_ok=True)

    video_src = Path(f"out/{episode_id}.mp4")
    if video_src.exists():
        shutil.copy2(video_src, release_dir / f"{episode_id}.mp4")

    artifacts = [
        (f"assets/frames/{episode_id}/storyboard_grid.png", "storyboard_grid.png"),
        ("state/storyboard.json", "storyboard.json"),
        ("state/topic.json", "topic.json"),
        ("assets/audio/timestamps.json", "timestamps.json"),
        ("assets/audio/voiceover.wav", "voiceover.wav"),
        ("state/captions.ass", "captions.ass")
    ]
    for src, dst in artifacts:
        p = Path(src)
        if p.exists():
            shutil.copy2(p, release_dir / dst)

    with open(release_dir / "QA_REPORT.json", "w", encoding="utf-8") as f:
        json.dump(qa_report, f, indent=2)

    log(f"[RELEASE V2] Archived complete high-tempo release bundle to: {release_dir.resolve()}")


def append_dynamic_pacing_report(episode: dict, qa_report: dict, attempt: int):
    report_file = Path("out/DYNAMIC_PACING_REPORT.md")
    report_file.parent.mkdir(parents=True, exist_ok=True)

    v_file = Path(f"out/{episode['id']}.mp4")
    file_size_mb = (v_file.stat().st_size / (1024 * 1024)) if v_file.exists() else 0.0

    entry = f"""
## Episode: {episode['title']} (`{episode['id']}`)
- **Status**: ✅ **PASS (ALL 5 HIGH-TEMPO PACING SCRUTINY VECTORS VERIFIED)**
- **Attempts Required**: {attempt} / {MAX_RETRIES}
- **Master File**: `out/releases_v2/{episode['id']}/{episode['id']}.mp4` ({file_size_mb:.2f} MB)
- **Visual QA Contact Sheet**: `out/releases_v2/{episode['id']}/storyboard_grid.png`
- **Multi-Agent QA Audit**:
  * **Vector 1 (Pacing & Motion)**: {qa_report.get('Vector 1 (Pacing & Motion)', {}).get('status')} - {qa_report.get('Vector 1 (Pacing & Motion)', {}).get('details')}
  * **Vector 2 (Audio Dynamics)**: {qa_report.get('Vector 2 (Audio Dynamics)', {}).get('status')} - {qa_report.get('Vector 2 (Audio Dynamics)', {}).get('details')}
  * **Vector 3 (Kinetic Captions & Sync)**: {qa_report.get('Vector 3 (Kinetic Captions)', {}).get('status')} - {qa_report.get('Vector 3 (Kinetic Captions)', {}).get('details')}
  * **Vector 4 (Container & Codec)**: {qa_report.get('Vector 4 (Container & Codec)', {}).get('status')} - {qa_report.get('Vector 4 (Container & Codec)', {}).get('details')}
  * **Vector 5 (Narrative Alignment)**: {qa_report.get('Vector 5 (Narrative Alignment)', {}).get('status')} - {qa_report.get('Vector 5 (Narrative Alignment)', {}).get('details')}

---
"""
    if not report_file.exists():
        header = "# High-Tempo Dynamic Pacing Production & Deep QA Report (12–16 Cuts)\n\nGenerated by Autonomous Multi-Agent Pipeline.\n\n"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(header + entry)
    else:
        with open(report_file, "a", encoding="utf-8") as f:
            f.write(entry)


def process_episode(episode: dict) -> bool:
    ep_id = episode["id"]
    ep_title = episode["title"]
    log(f"\n====================================================================")
    log(f" Starting High-Tempo Production for: {ep_title} ({ep_id})")
    log(f"====================================================================")

    release_qa = Path(f"out/releases_v2/{ep_id}/QA_REPORT.json")
    if release_qa.exists():
        try:
            with open(release_qa, "r", encoding="utf-8") as f:
                r_data = json.load(f)
            if r_data.get("overall") == "PASS":
                log(f"[SKIP] Episode {ep_id} already has a verified release v2 bundle. Skipping.")
                return True
        except Exception:
            pass

    for attempt in range(1, MAX_RETRIES + 1):
        log(f"--- Attempt {attempt}/{MAX_RETRIES} for {ep_id} ---")

        # Step A: Agent 1 - Mine topic
        if not run_step([
            sys.executable, ".agent/skills/topic-miner/scripts/mine_topics.py",
            "--topic-id", ep_id,
            "--output", "state/topic.json"
        ], f"Mining topic {ep_id}"):
            time.sleep(2)
            continue

        # Step B: Agent 1 - Generate 14-scene storyboard with dynamic clause binding
        if not run_step([
            sys.executable, ".agent/skills/video-scriptor/scripts/generate_storyboard.py",
            "--topic", "state/topic.json",
            "--output", "state/storyboard.json"
        ], f"Generating 14-scene high-tempo storyboard for {ep_id}"):
            time.sleep(2)
            continue

        # Step C: Agent 2 - Synthesize voiceover & word timestamps
        if not run_step([
            sys.executable, ".agent/skills/tts-audio-generator/scripts/synthesize.py",
            "--storyboard", "state/storyboard.json",
            "--output-audio", "assets/audio/voiceover.wav",
            "--output-timestamps", "assets/audio/timestamps.json",
            "--voice", "en-US-ChristopherNeural",
            "--rate", "+20%"
        ], f"Synthesizing voiceover narration for {ep_id}"):
            time.sleep(3)
            continue

        # Step D: Agent 2 - Batch-download keyframes in parallel (2 workers) via Pollinations Flux
        ep_frames_dir = Path(f"assets/frames/{ep_id}")
        ep_frames_dir.mkdir(parents=True, exist_ok=True)
        if not run_step([
            sys.executable, ".agent/skills/image-generator/scripts/generate_frames.py",
            "--storyboard", "state/storyboard.json",
            "--output-dir", str(ep_frames_dir),
            "--model", "flux",
            "--workers", "2"
        ], f"Batch rendering 14 keyframes in parallel for {ep_id}"):
            time.sleep(5)
            continue

        # Step E: Agent 2 - Visual contact sheet (4 columns for 14 scenes)
        run_step([
            sys.executable, ".agent/skills/image-generator/scripts/create_contact_sheet.py",
            "--frames-dir", str(ep_frames_dir),
            "--storyboard", "state/storyboard.json",
            "--output", str(ep_frames_dir / "storyboard_grid.png"),
            "--cols", "4"
        ], f"Compiling 14-scene contact sheet for {ep_id}")

        # Step F: Agent 3 - Compile 14-scene video with alternating Ken Burns & burned captions
        out_video = Path(f"out/{ep_id}.mp4")
        if not run_step([
            sys.executable, ".agent/skills/remotion-video-compiler/scripts/render_short.py",
            "--storyboard", "state/storyboard.json",
            "--audio", "assets/audio/voiceover.wav",
            "--timestamps", "assets/audio/timestamps.json",
            "--frames-dir", str(ep_frames_dir),
            "--bgm", "assets/bgm/soundtrack.wav",
            "--output", str(out_video)
        ], f"Compiling high-tempo short-form video for {ep_id}"):
            time.sleep(3)
            continue

        # Step G: Agent 4 - Multi-Vector Scrutiny Inspector
        qa_report_path = Path(f"out/{ep_id}_qa.json")
        cmd_qa = [
            sys.executable, ".agent/skills/video-verifier/scripts/deep_qa_inspector.py",
            "--video", str(out_video),
            "--storyboard", "state/storyboard.json",
            "--timestamps", "assets/audio/timestamps.json",
            "--report", str(qa_report_path)
        ]
        log(f"Running Agent 4 Multi-Vector QA Inspector on {out_video}...")
        qa_proc = subprocess.run(cmd_qa)

        qa_report = {}
        if qa_report_path.exists():
            try:
                with open(qa_report_path, "r", encoding="utf-8") as f:
                    qa_report = json.load(f)
            except Exception:
                pass

        if qa_proc.returncode == 0:
            log(f"[QA VERIFIED] Episode {ep_id} passed all 5 high-tempo scrutiny vectors!")
            archive_release_v2(ep_id, qa_report)
            append_dynamic_pacing_report(episode, qa_report, attempt)
            return True
        else:
            log(f"[QA FAILED] Attempt {attempt} failed assertions. Retrying self-healing loop...")
            time.sleep(3)

    log(f"[FATAL] Episode {ep_id} failed after {MAX_RETRIES} attempts.")
    return False


def main():
    log("====================================================================")
    log(" Autonomous High-Tempo Dynamic Pacing Batch (12-16 Cuts) Started")
    log(f" Queue length: {len(QUEUE)} episodes")
    log("====================================================================")

    results = {}
    for ep in QUEUE:
        success = process_episode(ep)
        results[ep["id"]] = success

    log("\n====================================================================")
    log(" Production Batch Summary:")
    for ep_id, status in results.items():
        log(f"  - {ep_id}: {'PASSED' if status else 'FAILED'}")
    log("====================================================================")

    all_passed = all(results.values())
    if all_passed:
        with open("out/STATUS.txt", "w", encoding="utf-8") as f:
            f.write("DYNAMIC_PACING_BATCH_ALL_EPISODES_VERIFIED\n")
        log("[COMPLETE] Full high-tempo queue verified and archived. Written to out/STATUS.txt.")
    sys.exit(0 if all_passed else 1)


if __name__ == "__main__":
    main()
